import { addDays, format } from "date-fns";
import { el } from "date-fns/locale";
import type {
  BusinessProfile,
  ParentDashboardData,
  QuizAttemptReview,
  Receipt,
  StudentDashboardData,
} from "@/lib/types/database";

/**
 * Hand-written, realistic-looking sample data for the public /demo page
 * (see app/demo/page.tsx) - never touches Supabase, so this is the only
 * source of truth for what the demo shows.
 *
 * Dates are computed relative to "now" (module load time), not fixed
 * literals - PortalUpcomingCard already projects the weekly schedule
 * forward from today, so fixed calendar-event/attendance dates would
 * silently drift into the past and stop showing up as this static page
 * ages. Recomputing on load keeps the demo looking current indefinitely.
 */

const today = new Date();
const isoDate = (dayOffset: number) => format(addDays(today, dayOffset), "yyyy-MM-dd");
const isoDateTime = (dayOffset: number, hour: number, minute: number) => {
  const d = addDays(today, dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};
const monthName = (dayOffset: number) =>
  format(addDays(today, dayOffset), "MMMM", { locale: el });

const NIKOS: StudentDashboardData = {
  student: {
    id: "demo-student-nikos",
    firstName: "Νίκος",
    lastName: "Παπαδόπουλος",
    gradeLevel: "Β Λυκείου",
    email: "nikos.papadopoulos@example.com",
    tuitionAmount: 90,
  },
  parents: [
    {
      name: "Ελένη Παπαδοπούλου",
      email: "eleni.papadopoulou@example.com",
      phone: "6971234567",
      is_primary: true,
    },
  ],
  classes: [
    // Has a start/finish date set - the other class deliberately doesn't,
    // to show both states (the fields are optional per class).
    {
      id: "demo-class-algebra-b",
      name: "Άλγεβρα Β Λυκείου",
      hoursPerWeek: 3,
      archivedAt: null,
      startDate: isoDate(-60),
      finishDate: isoDate(220),
    },
    { id: "demo-class-katefthynsis-b", name: "Μαθηματικά Κατεύθυνσης Β Λυκείου", hoursPerWeek: 2, archivedAt: null },
  ],
  schedules: [
    { class_id: "demo-class-algebra-b", day: "Mon", time: "17:00" },
    { class_id: "demo-class-algebra-b", day: "Wed", time: "17:00" },
    { class_id: "demo-class-algebra-b", day: "Thu", time: "17:00" },
    { class_id: "demo-class-katefthynsis-b", day: "Tue", time: "18:00" },
    { class_id: "demo-class-katefthynsis-b", day: "Fri", time: "18:00" },
  ],
  attendance: [
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-2), status: "present" },
    { class_id: "demo-class-katefthynsis-b", class_name: "Μαθηματικά Κατεύθυνσης Β Λυκείου", attendance_date: isoDate(-5), status: "present" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-7), status: "late" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-9), status: "present" },
    { class_id: "demo-class-katefthynsis-b", class_name: "Μαθηματικά Κατεύθυνσης Β Λυκείου", attendance_date: isoDate(-12), status: "absent" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-14), status: "present" },
    { class_id: "demo-class-katefthynsis-b", class_name: "Μαθηματικά Κατεύθυνσης Β Λυκείου", attendance_date: isoDate(-16), status: "present" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-19), status: "present" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-21), status: "late" },
    { class_id: "demo-class-katefthynsis-b", class_name: "Μαθηματικά Κατεύθυνσης Β Λυκείου", attendance_date: isoDate(-26), status: "present" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-28), status: "present" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-33), status: "absent" },
    { class_id: "demo-class-katefthynsis-b", class_name: "Μαθηματικά Κατεύθυνσης Β Λυκείου", attendance_date: isoDate(-40), status: "present" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-47), status: "present" },
    { class_id: "demo-class-katefthynsis-b", class_name: "Μαθηματικά Κατεύθυνσης Β Λυκείου", attendance_date: isoDate(-54), status: "late" },
    { class_id: "demo-class-algebra-b", class_name: "Άλγεβρα Β Λυκείου", attendance_date: isoDate(-61), status: "present" },
  ],
  quizzes: [
    {
      id: "demo-quiz-factoring",
      title: "Παραγοντοποίηση Πολυωνύμων",
      className: "Άλγεβρα Β Λυκείου",
      completed: true,
      score: 17,
      maxScore: 20,
      submittedAt: isoDateTime(-6, 18, 32),
      quizDeleted: false,
      // Retried once, fixed the one mistake, used up both allowed attempts.
      bestScore: 20,
      attemptsUsed: 2,
      maxAttempts: 2,
      canRetake: false,
    },
    {
      id: "demo-quiz-trig",
      title: "Τριγωνομετρικές Εξισώσεις",
      className: "Άλγεβρα Β Λυκείου",
      completed: false,
      score: null,
      maxScore: 20,
      submittedAt: null,
      quizDeleted: false,
      bestScore: null,
      attemptsUsed: 0,
      maxAttempts: null,
      canRetake: false,
    },
    {
      id: "demo-quiz-vectors",
      title: "Διανύσματα",
      className: "Μαθηματικά Κατεύθυνσης Β Λυκείου",
      completed: true,
      score: 10,
      maxScore: 20,
      submittedAt: isoDateTime(-20, 18, 5),
      quizDeleted: false,
      // Retried once, improved but still has one question wrong - and can
      // still retry again (unlimited attempts on this one).
      bestScore: 15,
      attemptsUsed: 2,
      maxAttempts: null,
      canRetake: true,
    },
    {
      id: "demo-quiz-polynomials",
      title: "Πράξεις Πολυωνύμων",
      className: "Άλγεβρα Β Λυκείου",
      completed: true,
      score: 19,
      maxScore: 20,
      submittedAt: isoDateTime(-34, 17, 40),
      quizDeleted: false,
      bestScore: 19,
      attemptsUsed: 1,
      maxAttempts: null,
      canRetake: false,
    },
    {
      id: "demo-quiz-inequalities",
      title: "Ανισώσεις",
      className: "Άλγεβρα Β Λυκείου",
      completed: true,
      score: 14,
      maxScore: 20,
      submittedAt: isoDateTime(-48, 17, 55),
      quizDeleted: false,
      // Hasn't retried yet, but still can (up to 3 attempts) - the other
      // retake-related demo quizzes show what happens after retrying; this
      // one shows the "Επανάληψη" button before that.
      bestScore: 14,
      attemptsUsed: 1,
      maxAttempts: 3,
      canRetake: true,
    },
    {
      id: "demo-quiz-functions",
      title: "Συναρτήσεις",
      className: "Μαθηματικά Κατεύθυνσης Β Λυκείου",
      completed: true,
      score: 18,
      maxScore: 20,
      submittedAt: isoDateTime(-55, 18, 10),
      quizDeleted: false,
      bestScore: 18,
      attemptsUsed: 1,
      maxAttempts: null,
      canRetake: false,
    },
  ],
  calendarEvents: [
    {
      id: "demo-event-extra",
      event_type: "extra_session",
      event_date: isoDate(4),
      start_time: "17:00",
      end_time: "18:30",
      class_id: "demo-class-algebra-b",
      class_name: "Άλγεβρα Β Λυκείου",
      notes: "Επανάληψη πριν το διαγώνισμα",
    },
    {
      id: "demo-event-cancel",
      event_type: "cancellation",
      event_date: isoDate(11),
      start_time: "18:00",
      end_time: "19:30",
      class_id: "demo-class-katefthynsis-b",
      class_name: "Μαθηματικά Κατεύθυνσης Β Λυκείου",
      notes: "Αργία",
    },
  ],
  assessments: [
    {
      id: "demo-assessment-assignment-nikos-mock-exam",
      assessmentId: "demo-assessment-nikos-mock-exam",
      kind: "mock_exam",
      title: "Προσομοίωση Πανελληνίων - Α' Τετράμηνο",
      description: "Ύλη: Άλγεβρα κεφ. 1-4 (πολυώνυμα, εξισώσεις, ανισώσεις)",
      className: "Άλγεβρα Β Λυκείου",
      maxScore: 100,
      effectiveScheduledDate: isoDate(12),
      effectiveScheduledTime: "09:00",
      effectiveDeadlineAt: null,
      status: "registered",
      score: null,
      teacherComment: null,
      isLate: false,
    },
    {
      id: "demo-assessment-assignment-nikos-trig",
      assessmentId: "demo-assessment-nikos-trig",
      kind: "short_assessment",
      title: "Τεστ: Τριγωνομετρικές Εξισώσεις",
      description: "Ύλη: Κεφ. 5, ασκήσεις 1-20",
      className: "Άλγεβρα Β Λυκείου",
      maxScore: 20,
      effectiveScheduledDate: null,
      effectiveScheduledTime: null,
      effectiveDeadlineAt: isoDateTime(5, 23, 59),
      status: "registered",
      score: null,
      teacherComment: null,
      isLate: false,
    },
    {
      // Marked but was taken after its deadline - demonstrates that the
      // "late" badge persists even once a mark is entered.
      id: "demo-assessment-assignment-nikos-vectors",
      assessmentId: "demo-assessment-nikos-vectors",
      kind: "short_assessment",
      title: "Τεστ: Διανύσματα",
      description: "Ύλη: Πρόσθεση/αφαίρεση διανυσμάτων, εσωτερικό γινόμενο",
      className: "Μαθηματικά Κατεύθυνσης Β Λυκείου",
      maxScore: 20,
      effectiveScheduledDate: null,
      effectiveScheduledTime: null,
      effectiveDeadlineAt: isoDateTime(-10, 23, 59),
      status: "marked",
      score: 14,
      teacherComment: "Καλή προσπάθεια, πρόσεχε τις πράξεις με το εσωτερικό γινόμενο.",
      isLate: true,
    },
    {
      // Submitted, waiting on a mark - the third state in the
      // registered -> taken -> marked lifecycle, not otherwise shown here.
      id: "demo-assessment-assignment-nikos-inequalities",
      assessmentId: "demo-assessment-nikos-inequalities",
      kind: "short_assessment",
      title: "Τεστ: Ανισώσεις",
      description: "Ύλη: Κεφ. 6, γραμμικές και τετραγωνικές ανισώσεις",
      className: "Άλγεβρα Β Λυκείου",
      maxScore: 20,
      effectiveScheduledDate: null,
      effectiveScheduledTime: null,
      effectiveDeadlineAt: isoDateTime(-2, 23, 59),
      status: "taken",
      score: null,
      teacherComment: null,
      isLate: false,
    },
    {
      id: "demo-assessment-assignment-nikos-factoring",
      assessmentId: "demo-assessment-nikos-factoring",
      kind: "short_assessment",
      title: "Τεστ: Παραγοντοποίηση",
      description: "Ύλη: Κεφ. 3, παραγοντοποίηση πολυωνύμων",
      className: "Άλγεβρα Β Λυκείου",
      maxScore: 20,
      effectiveScheduledDate: null,
      effectiveScheduledTime: null,
      effectiveDeadlineAt: isoDateTime(-20, 23, 59),
      status: "marked",
      score: 18,
      teacherComment: "Πολύ καλή δουλειά!",
      isLate: false,
    },
  ],
};

// Canned full answer review for the "Ανασκόπηση" button on the demo's
// completed quizzes - the real page fetches this from getQuizReviewAction,
// which needs a live authenticated session the public /demo page doesn't
// have. Only these two hand-picked quizzes get one (factoring: retried once,
// attempts maxed out, aced it; vectors: retried once, improved but still
// retriable) - every other "Ανασκόπηση" click falls through to the real
// (failing) action, same as before this existed.
export const DEMO_STUDENT_QUIZ_REVIEWS: Record<string, QuizAttemptReview> = {
  "demo-quiz-factoring": {
    attemptId: "demo-attempt-factoring",
    quizId: "demo-quiz-factoring",
    quizTitle: "Παραγοντοποίηση Πολυωνύμων",
    score: 17,
    maxScore: 20,
    submittedAt: isoDateTime(-6, 18, 32),
    attemptsUsed: 2,
    maxAttempts: 2,
    canRetake: false,
    best: {
      score: 20,
      submittedAt: isoDateTime(-2, 19, 10),
      answers: [
        {
          answerId: "demo-best-answer-1",
          questionId: "demo-question-1",
          questionText: "Ποιο είναι το ανάπτυγμα του $(x+3)^2$;",
          questionType: "multiple_choice",
          imageUrl: null,
          selectedOptionId: "demo-option-1b",
          selectedOptionText: "$x^2 + 6x + 9$",
          textAnswer: null,
          correctOptionId: "demo-option-1b",
          correctOptionText: "$x^2 + 6x + 9$",
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: null,
        },
        {
          answerId: "demo-best-answer-2",
          questionId: "demo-question-2",
          questionText: "Παραγοντοποίησε: $x^2 - 9$",
          questionType: "short_answer",
          imageUrl: null,
          selectedOptionId: null,
          selectedOptionText: null,
          textAnswer: "(x-3)(x+3)",
          correctOptionId: null,
          correctOptionText: null,
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: null,
        },
        {
          answerId: "demo-best-answer-3",
          questionId: "demo-question-3",
          questionText: "Ποιο είναι το ανάπτυγμα του $(x-2)(x+2)$;",
          questionType: "multiple_choice",
          imageUrl: null,
          selectedOptionId: "demo-option-3a",
          selectedOptionText: "$x^2 - 4$",
          textAnswer: null,
          correctOptionId: "demo-option-3a",
          correctOptionText: "$x^2 - 4$",
          isCorrect: true,
          pointsAwarded: 7,
          pointsPossible: 7,
          teacherComment: null,
        },
        {
          answerId: "demo-best-answer-4",
          questionId: "demo-question-4",
          questionText: "Παραγοντοποίησε: $x^2 + 5x + 6$",
          questionType: "short_answer",
          imageUrl: null,
          selectedOptionId: null,
          selectedOptionText: null,
          textAnswer: "(x+2)(x+3)",
          correctOptionId: null,
          correctOptionText: null,
          isCorrect: true,
          pointsAwarded: 3,
          pointsPossible: 3,
          teacherComment: "Σωστή διόρθωση - ακριβώς αυτό εννοούσα!",
        },
      ],
    },
    answers: [
      {
        answerId: "demo-answer-1",
        questionId: "demo-question-1",
        questionText: "Ποιο είναι το ανάπτυγμα του $(x+3)^2$;",
        questionType: "multiple_choice",
        imageUrl: null,
        selectedOptionId: "demo-option-1b",
        selectedOptionText: "$x^2 + 6x + 9$",
        textAnswer: null,
        correctOptionId: "demo-option-1b",
        correctOptionText: "$x^2 + 6x + 9$",
        isCorrect: true,
        pointsAwarded: 5,
        pointsPossible: 5,
        teacherComment: null,
      },
      {
        answerId: "demo-answer-2",
        questionId: "demo-question-2",
        questionText: "Παραγοντοποίησε: $x^2 - 9$",
        questionType: "short_answer",
        imageUrl: null,
        selectedOptionId: null,
        selectedOptionText: null,
        textAnswer: "(x-3)(x+3)",
        correctOptionId: null,
        correctOptionText: null,
        isCorrect: true,
        pointsAwarded: 5,
        pointsPossible: 5,
        teacherComment:
          "Πολύ καλή δουλειά! Σωστή χρήση της διαφοράς τετραγώνων.",
      },
      {
        answerId: "demo-answer-3",
        questionId: "demo-question-3",
        questionText: "Ποιο είναι το ανάπτυγμα του $(x-2)(x+2)$;",
        questionType: "multiple_choice",
        imageUrl: null,
        selectedOptionId: "demo-option-3a",
        selectedOptionText: "$x^2 - 4$",
        textAnswer: null,
        correctOptionId: "demo-option-3a",
        correctOptionText: "$x^2 - 4$",
        isCorrect: true,
        pointsAwarded: 7,
        pointsPossible: 7,
        teacherComment: null,
      },
      {
        answerId: "demo-answer-4",
        questionId: "demo-question-4",
        questionText: "Παραγοντοποίησε: $x^2 + 5x + 6$",
        questionType: "short_answer",
        imageUrl: null,
        selectedOptionId: null,
        selectedOptionText: null,
        textAnswer: "(x+2)(x+4)",
        correctOptionId: null,
        correctOptionText: null,
        isCorrect: false,
        pointsAwarded: 0,
        pointsPossible: 3,
        teacherComment:
          "Πρόσεξε: το γινόμενο των αριθμών πρέπει να είναι 6 και το άθροισμά τους 5 - δοκίμασε ξανά τους παράγοντες.",
      },
    ],
  },
  // A retry that improves but doesn't fully fix everything - and is still
  // retriable, unlike demo-quiz-factoring above (attempts maxed out) - two
  // different points along the same feature, shown side by side.
  "demo-quiz-vectors": {
    attemptId: "demo-attempt-vectors",
    quizId: "demo-quiz-vectors",
    quizTitle: "Διανύσματα",
    score: 10,
    maxScore: 20,
    submittedAt: isoDateTime(-20, 18, 5),
    attemptsUsed: 2,
    maxAttempts: null,
    canRetake: true,
    best: {
      score: 15,
      submittedAt: isoDateTime(-18, 18, 45),
      answers: [
        {
          answerId: "demo-vectors-best-answer-1",
          questionId: "demo-vectors-question-1",
          questionText: "Αν $\\vec{a} = (2, 3)$ και $\\vec{b} = (1, -1)$, βρες το $\\vec{a} + \\vec{b}$.",
          questionType: "multiple_choice",
          imageUrl: null,
          selectedOptionId: "demo-vectors-option-1a",
          selectedOptionText: "(3, 2)",
          textAnswer: null,
          correctOptionId: "demo-vectors-option-1a",
          correctOptionText: "(3, 2)",
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: null,
        },
        {
          answerId: "demo-vectors-best-answer-2",
          questionId: "demo-vectors-question-2",
          questionText: "Υπολόγισε το εσωτερικό γινόμενο $\\vec{a} \\cdot \\vec{b}$ για $\\vec{a} = (2, 3)$, $\\vec{b} = (1, -1)$.",
          questionType: "short_answer",
          imageUrl: null,
          selectedOptionId: null,
          selectedOptionText: null,
          textAnswer: "-1",
          correctOptionId: null,
          correctOptionText: null,
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: "Σωστά τώρα! Πρόσθεσες σωστά τα γινόμενα.",
        },
        {
          answerId: "demo-vectors-best-answer-3",
          questionId: "demo-vectors-question-3",
          questionText: "Ποιο είναι το μέτρο του διανύσματος $\\vec{a} = (3, 4)$;",
          questionType: "short_answer",
          imageUrl: null,
          selectedOptionId: null,
          selectedOptionText: null,
          textAnswer: "7",
          correctOptionId: null,
          correctOptionText: null,
          isCorrect: false,
          pointsAwarded: 0,
          pointsPossible: 5,
          teacherComment:
            "Ακόμα λάθος - το μέτρο είναι $\\sqrt{3^2+4^2}$, όχι το άθροισμα των συντεταγμένων.",
        },
        {
          answerId: "demo-vectors-best-answer-4",
          questionId: "demo-vectors-question-4",
          questionText: "Τα διανύσματα $(2, 4)$ και $(1, 2)$ είναι παράλληλα;",
          questionType: "true_false",
          imageUrl: null,
          selectedOptionId: "demo-vectors-option-4a",
          selectedOptionText: "Ναι",
          textAnswer: null,
          correctOptionId: "demo-vectors-option-4a",
          correctOptionText: "Ναι",
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: null,
        },
      ],
    },
    answers: [
      {
        answerId: "demo-vectors-answer-1",
        questionId: "demo-vectors-question-1",
        questionText: "Αν $\\vec{a} = (2, 3)$ και $\\vec{b} = (1, -1)$, βρες το $\\vec{a} + \\vec{b}$.",
        questionType: "multiple_choice",
        imageUrl: null,
        selectedOptionId: "demo-vectors-option-1a",
        selectedOptionText: "(3, 2)",
        textAnswer: null,
        correctOptionId: "demo-vectors-option-1a",
        correctOptionText: "(3, 2)",
        isCorrect: true,
        pointsAwarded: 5,
        pointsPossible: 5,
        teacherComment: null,
      },
      {
        answerId: "demo-vectors-answer-2",
        questionId: "demo-vectors-question-2",
        questionText: "Υπολόγισε το εσωτερικό γινόμενο $\\vec{a} \\cdot \\vec{b}$ για $\\vec{a} = (2, 3)$, $\\vec{b} = (1, -1)$.",
        questionType: "short_answer",
        imageUrl: null,
        selectedOptionId: null,
        selectedOptionText: null,
        textAnswer: "5",
        correctOptionId: null,
        correctOptionText: null,
        isCorrect: false,
        pointsAwarded: 0,
        pointsPossible: 5,
        teacherComment:
          "Ξαναδές τον τύπο: $\\vec{a} \\cdot \\vec{b} = a_1 b_1 + a_2 b_2$, όχι απλή πρόσθεση.",
      },
      {
        answerId: "demo-vectors-answer-3",
        questionId: "demo-vectors-question-3",
        questionText: "Ποιο είναι το μέτρο του διανύσματος $\\vec{a} = (3, 4)$;",
        questionType: "short_answer",
        imageUrl: null,
        selectedOptionId: null,
        selectedOptionText: null,
        textAnswer: "7",
        correctOptionId: null,
        correctOptionText: null,
        isCorrect: false,
        pointsAwarded: 0,
        pointsPossible: 5,
        teacherComment: null,
      },
      {
        answerId: "demo-vectors-answer-4",
        questionId: "demo-vectors-question-4",
        questionText: "Τα διανύσματα $(2, 4)$ και $(1, 2)$ είναι παράλληλα;",
        questionType: "true_false",
        imageUrl: null,
        selectedOptionId: "demo-vectors-option-4a",
        selectedOptionText: "Ναι",
        textAnswer: null,
        correctOptionId: "demo-vectors-option-4a",
        correctOptionText: "Ναι",
        isCorrect: true,
        pointsAwarded: 5,
        pointsPossible: 5,
        teacherComment: null,
      },
    ],
  },
};

const MARIA: ParentDashboardData["kids"][number] = {
  student: {
    id: "demo-student-maria",
    firstName: "Μαρία",
    lastName: "Παπαδοπούλου",
    gradeLevel: "Α Γυμνασίου",
    email: null,
    tuitionAmount: 70,
    withdrawnAt: null,
  },
  classes: [
    { id: "demo-class-gym-a", name: "Μαθηματικά Α Γυμνασίου", hoursPerWeek: 2, archivedAt: null },
  ],
  schedules: [
    { class_id: "demo-class-gym-a", day: "Tue", time: "16:00" },
    { class_id: "demo-class-gym-a", day: "Thu", time: "16:00" },
  ],
  attendance: [
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-3), status: "present" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-5), status: "present" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-10), status: "present" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-12), status: "late" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-17), status: "present" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-19), status: "present" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-24), status: "absent" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-31), status: "present" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-38), status: "present" },
    { class_id: "demo-class-gym-a", class_name: "Μαθηματικά Α Γυμνασίου", attendance_date: isoDate(-45), status: "late" },
  ],
  quizzes: [
    {
      id: "demo-quiz-fractions",
      title: "Πράξεις με Κλάσματα",
      className: "Μαθηματικά Α Γυμνασίου",
      completed: true,
      score: 19,
      maxScore: 20,
      submittedAt: isoDateTime(-9, 17, 20),
      quizDeleted: false,
      bestScore: 19,
      attemptsUsed: 1,
      maxAttempts: null,
      canRetake: false,
    },
    {
      id: "demo-quiz-maria-decimals",
      title: "Δεκαδικοί Αριθμοί",
      className: "Μαθηματικά Α Γυμνασίου",
      completed: true,
      score: 16,
      maxScore: 20,
      submittedAt: isoDateTime(-23, 16, 45),
      quizDeleted: false,
      // Retried once and improved - attempts used up.
      bestScore: 19,
      attemptsUsed: 2,
      maxAttempts: 2,
      canRetake: false,
    },
    {
      id: "demo-quiz-maria-geometry",
      title: "Γεωμετρικά Σχήματα",
      className: "Μαθηματικά Α Γυμνασίου",
      completed: true,
      score: 20,
      maxScore: 20,
      submittedAt: isoDateTime(-37, 16, 15),
      quizDeleted: false,
      bestScore: 20,
      attemptsUsed: 1,
      maxAttempts: null,
      canRetake: false,
    },
    {
      id: "demo-quiz-maria-equations",
      title: "Απλές Εξισώσεις",
      className: "Μαθηματικά Α Γυμνασίου",
      completed: true,
      score: 17,
      maxScore: 20,
      submittedAt: isoDateTime(-44, 16, 30),
      quizDeleted: false,
      // Hasn't retried yet, but still can - shown here instead of the
      // student dashboard's own inequalities quiz so a parent sees this
      // state too, not just after-the-fact best scores.
      bestScore: 17,
      attemptsUsed: 1,
      maxAttempts: 2,
      canRetake: true,
    },
    {
      id: "demo-quiz-maria-ratios",
      title: "Αναλογίες",
      className: "Μαθηματικά Α Γυμνασίου",
      completed: false,
      score: null,
      maxScore: 20,
      submittedAt: null,
      quizDeleted: false,
      bestScore: null,
      attemptsUsed: 0,
      maxAttempts: null,
      canRetake: false,
    },
  ],
  calendarEvents: [
    {
      id: "demo-event-maria-extra",
      event_type: "extra_session",
      event_date: isoDate(3),
      start_time: "16:00",
      end_time: "17:00",
      class_id: "demo-class-gym-a",
      class_name: "Μαθηματικά Α Γυμνασίου",
      notes: "Προετοιμασία για διαγώνισμα",
    },
  ],
  assessments: [
    {
      id: "demo-assessment-assignment-maria-decimals",
      assessmentId: "demo-assessment-maria-decimals",
      kind: "short_assessment",
      title: "Τεστ: Δεκαδικοί Αριθμοί",
      description: "Ύλη: Πρόσθεση, αφαίρεση, πολλαπλασιασμός δεκαδικών",
      className: "Μαθηματικά Α Γυμνασίου",
      maxScore: 20,
      effectiveScheduledDate: null,
      effectiveScheduledTime: null,
      effectiveDeadlineAt: isoDateTime(6, 23, 59),
      status: "registered",
      score: null,
      teacherComment: null,
      isLate: false,
    },
    {
      id: "demo-assessment-assignment-maria-fractions",
      assessmentId: "demo-assessment-maria-fractions",
      kind: "short_assessment",
      title: "Τεστ: Κλάσματα",
      description: "Ύλη: Ισοδύναμα κλάσματα, πρόσθεση κλασμάτων",
      className: "Μαθηματικά Α Γυμνασίου",
      maxScore: 20,
      effectiveScheduledDate: null,
      effectiveScheduledTime: null,
      effectiveDeadlineAt: isoDateTime(-15, 23, 59),
      status: "marked",
      score: 17,
      teacherComment: "Πολύ καλά, μόνο μια απροσεξία στην τελευταία άσκηση.",
      isLate: false,
    },
  ],
};

const NIKOS_AS_CHILD: ParentDashboardData["kids"][number] = {
  student: { ...NIKOS.student, withdrawnAt: null },
  classes: NIKOS.classes,
  schedules: NIKOS.schedules,
  attendance: NIKOS.attendance,
  quizzes: NIKOS.quizzes,
  calendarEvents: NIKOS.calendarEvents,
  assessments: NIKOS.assessments,
};

export const DEMO_STUDENT_DASHBOARD: StudentDashboardData = NIKOS;

export const DEMO_PARENT_DASHBOARD: ParentDashboardData = {
  parent: {
    id: "demo-parent-eleni",
    name: "Ελένη Παπαδοπούλου",
    email: "eleni.papadopoulou@example.com",
    phone: "6971234567",
    isPrimary: true,
  },
  allParents: [
    {
      name: "Ελένη Παπαδοπούλου",
      email: "eleni.papadopoulou@example.com",
      phone: "6971234567",
      is_primary: true,
    },
    {
      name: "Γιώργος Παπαδόπουλος",
      email: "giorgos.papadopoulos@example.com",
      phone: "6981234567",
      is_primary: false,
    },
  ],
  kids: [NIKOS_AS_CHILD, MARIA],
  balance: {
    amount: 25,
    monthlyAmount: 140,
    recentTransactions: [
      {
        id: "demo-txn-charge",
        type: "monthly_charge",
        amount: 140,
        description: `Δίδακτρα ${monthName(-5)}`,
        createdAt: isoDateTime(-5, 8, 0),
        receiptId: null,
      },
      {
        id: "demo-txn-payment",
        type: "payment",
        amount: -115,
        description: "Πληρωμή μετρητοίς",
        createdAt: isoDateTime(-3, 10, 15),
        receiptId: "demo-receipt-recent",
      },
      {
        id: "demo-txn-charge-2",
        type: "monthly_charge",
        amount: 140,
        description: `Δίδακτρα ${monthName(-35)}`,
        createdAt: isoDateTime(-35, 8, 0),
        receiptId: null,
      },
      {
        id: "demo-txn-payment-2",
        type: "payment",
        amount: -140,
        description: "Πληρωμή με κάρτα",
        createdAt: isoDateTime(-33, 11, 0),
        receiptId: "demo-receipt-month2",
      },
      {
        id: "demo-txn-charge-3",
        type: "monthly_charge",
        amount: 140,
        description: `Δίδακτρα ${monthName(-65)}`,
        createdAt: isoDateTime(-65, 8, 0),
        receiptId: null,
      },
      {
        id: "demo-txn-payment-3",
        type: "payment",
        amount: -140,
        description: "Πληρωμή με κάρτα",
        createdAt: isoDateTime(-63, 11, 0),
        receiptId: null,
      },
      {
        id: "demo-txn-charge-4",
        type: "monthly_charge",
        amount: 140,
        description: `Δίδακτρα ${monthName(-95)}`,
        createdAt: isoDateTime(-95, 8, 0),
        receiptId: null,
      },
      {
        id: "demo-txn-payment-4",
        type: "payment",
        amount: -140,
        description: "Πληρωμή μετρητοίς",
        createdAt: isoDateTime(-93, 10, 0),
        receiptId: null,
      },
    ],
  },
  receipts: [
    {
      id: "demo-receipt-recent",
      series: "Α",
      receipt_number: 42,
      issue_date: isoDate(-3),
      recipient_name: "Ελένη Παπαδοπούλου",
      recipient_afm: null,
      recipient_address: null,
      family_id: "demo-family-papadopoulos",
      total_amount: 115,
      vat_category: "exempt_article_27",
      payment_method: 3,
      notes: null,
      mydata_status: "submitted",
      mydata_mark: "400012345678901",
      mydata_uid: "demo-uid-42",
      mydata_error: null,
      mydata_submitted_at: isoDateTime(-3, 10, 20),
      mydata_environment: "production",
      mydata_last_verified_at: isoDateTime(-3, 10, 25),
      mydata_last_verified_ok: true,
      mydata_warning: null,
      emailed_at: null,
      created_at: isoDateTime(-3, 10, 15),
      counts_toward_balance: true,
      lineItems: [
        {
          id: "demo-li-recent-1",
          student_id: "demo-student-nikos",
          description: `Δίδακτρα ${monthName(-3)} - Νίκος`,
          amount: 115,
          order_index: 0,
        },
      ],
    },
    {
      id: "demo-receipt-month2",
      series: "Α",
      receipt_number: 41,
      issue_date: isoDate(-33),
      recipient_name: "Ελένη Παπαδοπούλου",
      recipient_afm: null,
      recipient_address: null,
      family_id: "demo-family-papadopoulos",
      total_amount: 140,
      vat_category: "exempt_article_27",
      payment_method: 7,
      notes: null,
      mydata_status: "submitted",
      mydata_mark: "400012345678888",
      mydata_uid: "demo-uid-41",
      mydata_error: null,
      mydata_submitted_at: isoDateTime(-33, 11, 5),
      mydata_environment: "production",
      mydata_last_verified_at: isoDateTime(-33, 11, 10),
      mydata_last_verified_ok: true,
      mydata_warning: null,
      emailed_at: null,
      created_at: isoDateTime(-33, 11, 0),
      counts_toward_balance: true,
      lineItems: [
        {
          id: "demo-li-month2-1",
          student_id: "demo-student-nikos",
          description: `Δίδακτρα ${monthName(-33)} - Νίκος`,
          amount: 90,
          order_index: 0,
        },
        {
          id: "demo-li-month2-2",
          student_id: "demo-student-maria",
          description: `Δίδακτρα ${monthName(-33)} - Μαρία`,
          amount: 50,
          order_index: 1,
        },
      ],
    },
  ] satisfies Receipt[],
  business: {
    id: 1,
    business_name: "Modus — Φροντιστήριο Μαθηματικών",
    afm: "123456789",
    doy: "Καρδίτσας",
    activity_code: "85592000",
    address: "Καρδίτσα",
    city: "Καρδίτσα",
    postal_code: "43100",
    phone: "6971234567",
    updated_at: isoDateTime(-90, 9, 0),
  } satisfies BusinessProfile,
};
