import { addDays, format } from "date-fns";
import { el, enUS } from "date-fns/locale";
import type {
  BusinessProfile,
  ParentDashboardData,
  QuizAttemptReview,
  Receipt,
  StudentDashboardData,
} from "@/lib/types/database";

/**
 * English counterpart to lib/demo-data.ts, for the public /demo-en preview
 * page - same idea (hand-written, realistic-looking sample data, dates
 * computed relative to "now" so the page never looks stale), just an
 * English-speaking family instead of a Greek one. Not linked from the
 * homepage yet - reachable only by going directly to /demo-en.
 */

const today = new Date();
const isoDate = (dayOffset: number) => format(addDays(today, dayOffset), "yyyy-MM-dd");
const isoDateTime = (dayOffset: number, hour: number, minute: number) => {
  const d = addDays(today, dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};
const monthName = (dayOffset: number) =>
  format(addDays(today, dayOffset), "MMMM", { locale: enUS });
// The receipt itself is a Greek legal document (see the receipts comment
// below) - its line items use the Greek month name, not the English one
// used for the informal balance-transaction descriptions elsewhere.
const greekMonthName = (dayOffset: number) =>
  format(addDays(today, dayOffset), "MMMM", { locale: el });

const ALEX: StudentDashboardData = {
  student: {
    id: "demo-en-student-alex",
    firstName: "Alex",
    lastName: "Johnson",
    gradeLevel: "10th Grade",
    email: "alex.johnson@example.com",
    tuitionAmount: 90,
  },
  parents: [
    {
      name: "Lisa Johnson",
      email: "lisa.johnson@example.com",
      phone: "555-123-4567",
      is_primary: true,
    },
  ],
  classes: [
    // Has a start/finish date set - the other class deliberately doesn't,
    // to show both states (the fields are optional per class).
    {
      id: "demo-en-class-algebra-2",
      name: "Algebra II",
      hoursPerWeek: 3,
      archivedAt: null,
      startDate: isoDate(-60),
      finishDate: isoDate(220),
    },
    {
      id: "demo-en-class-precalc",
      name: "Pre-Calculus",
      hoursPerWeek: 2,
      archivedAt: null,
    },
  ],
  schedules: [
    { class_id: "demo-en-class-algebra-2", day: "Mon", time: "17:00" },
    { class_id: "demo-en-class-algebra-2", day: "Wed", time: "17:00" },
    { class_id: "demo-en-class-algebra-2", day: "Thu", time: "17:00" },
    { class_id: "demo-en-class-precalc", day: "Tue", time: "18:00" },
    { class_id: "demo-en-class-precalc", day: "Fri", time: "18:00" },
  ],
  attendance: [
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-2), status: "present" },
    { class_id: "demo-en-class-precalc", class_name: "Pre-Calculus", attendance_date: isoDate(-5), status: "present" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-7), status: "late" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-9), status: "present" },
    { class_id: "demo-en-class-precalc", class_name: "Pre-Calculus", attendance_date: isoDate(-12), status: "absent" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-14), status: "present" },
    { class_id: "demo-en-class-precalc", class_name: "Pre-Calculus", attendance_date: isoDate(-16), status: "present" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-19), status: "present" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-21), status: "late" },
    { class_id: "demo-en-class-precalc", class_name: "Pre-Calculus", attendance_date: isoDate(-26), status: "present" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-28), status: "present" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-33), status: "absent" },
    { class_id: "demo-en-class-precalc", class_name: "Pre-Calculus", attendance_date: isoDate(-40), status: "present" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-47), status: "present" },
    { class_id: "demo-en-class-precalc", class_name: "Pre-Calculus", attendance_date: isoDate(-54), status: "late" },
    { class_id: "demo-en-class-algebra-2", class_name: "Algebra II", attendance_date: isoDate(-61), status: "present" },
  ],
  quizzes: [
    {
      id: "demo-en-quiz-factoring",
      title: "Factoring Polynomials",
      className: "Algebra II",
      completed: true,
      score: 17,
      maxScore: 20,
      submittedAt: isoDateTime(-6, 18, 32),
      quizDeleted: false,
      // Retried once, fixed the one mistake, used up both allowed attempts.
      bestScore: 20,
      attemptsUsed: 2,
      maxAttempts: 2,
      canRetake: false,
    },
    {
      id: "demo-en-quiz-trig",
      title: "Trigonometric Equations",
      className: "Algebra II",
      completed: false,
      score: null,
      maxScore: 20,
      submittedAt: null,
      quizDeleted: false,
      bestScore: null,
      attemptsUsed: 0,
      maxAttempts: null,
      canRetake: false,
    },
    {
      id: "demo-en-quiz-vectors",
      title: "Vectors",
      className: "Pre-Calculus",
      completed: true,
      score: 10,
      maxScore: 20,
      submittedAt: isoDateTime(-20, 18, 5),
      quizDeleted: false,
      // Retried once, improved but still has one question wrong - and can
      // still retry again (unlimited attempts on this one).
      bestScore: 15,
      attemptsUsed: 2,
      maxAttempts: null,
      canRetake: true,
    },
    {
      id: "demo-en-quiz-polynomials",
      title: "Polynomial Operations",
      className: "Algebra II",
      completed: true,
      score: 19,
      maxScore: 20,
      submittedAt: isoDateTime(-34, 17, 40),
      quizDeleted: false,
      bestScore: 19,
      attemptsUsed: 1,
      maxAttempts: null,
      canRetake: false,
    },
    {
      id: "demo-en-quiz-inequalities",
      title: "Inequalities",
      className: "Algebra II",
      completed: true,
      score: 14,
      maxScore: 20,
      submittedAt: isoDateTime(-48, 17, 55),
      quizDeleted: false,
      // Hasn't retried yet, but still can - shows the "before retrying"
      // state alongside the two quizzes above that already show "after".
      bestScore: 14,
      attemptsUsed: 1,
      maxAttempts: 3,
      canRetake: true,
    },
    {
      id: "demo-en-quiz-functions",
      title: "Functions",
      className: "Pre-Calculus",
      completed: true,
      score: 18,
      maxScore: 20,
      submittedAt: isoDateTime(-55, 18, 10),
      quizDeleted: false,
      bestScore: 18,
      attemptsUsed: 1,
      maxAttempts: null,
      canRetake: false,
    },
  ],
  calendarEvents: [
    {
      id: "demo-en-event-extra",
      event_type: "extra_session",
      event_date: isoDate(4),
      start_time: "17:00",
      end_time: "18:30",
      class_id: "demo-en-class-algebra-2",
      class_name: "Algebra II",
      notes: "Review session before the test",
    },
    {
      id: "demo-en-event-cancel",
      event_type: "cancellation",
      event_date: isoDate(11),
      start_time: "18:00",
      end_time: "19:30",
      class_id: "demo-en-class-precalc",
      class_name: "Pre-Calculus",
      notes: "Public holiday",
    },
  ],
};

// Canned full answer review for the "Review" button on the demo's
// completed quizzes - the real page fetches this from getQuizReviewAction,
// which needs a live authenticated session the public /demo-en page
// doesn't have. Only these two hand-picked quizzes get one (factoring:
// retried once, attempts maxed out, aced it; vectors: retried once,
// improved but still retriable) - every other "Review" click falls
// through to the real (failing) action, same as the Greek demo.
export const DEMO_EN_STUDENT_QUIZ_REVIEWS: Record<string, QuizAttemptReview> = {
  "demo-en-quiz-factoring": {
    attemptId: "demo-en-attempt-factoring",
    quizId: "demo-en-quiz-factoring",
    quizTitle: "Factoring Polynomials",
    score: 17,
    maxScore: 20,
    submittedAt: isoDateTime(-6, 18, 32),
    attemptsUsed: 2,
    maxAttempts: 2,
    canRetake: false,
    best: {
      score: 20,
      submittedAt: isoDateTime(-2, 19, 10),
      answers: [
        {
          answerId: "demo-en-best-answer-1",
          questionId: "demo-en-question-1",
          questionText: "What is the expansion of $(x+3)^2$?",
          questionType: "multiple_choice",
          imageUrl: null,
          selectedOptionId: "demo-en-option-1b",
          selectedOptionText: "$x^2 + 6x + 9$",
          textAnswer: null,
          correctOptionId: "demo-en-option-1b",
          correctOptionText: "$x^2 + 6x + 9$",
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: null,
        },
        {
          answerId: "demo-en-best-answer-2",
          questionId: "demo-en-question-2",
          questionText: "Factor: $x^2 - 9$",
          questionType: "short_answer",
          imageUrl: null,
          selectedOptionId: null,
          selectedOptionText: null,
          textAnswer: "(x-3)(x+3)",
          correctOptionId: null,
          correctOptionText: null,
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: null,
        },
        {
          answerId: "demo-en-best-answer-3",
          questionId: "demo-en-question-3",
          questionText: "What is the expansion of $(x-2)(x+2)$?",
          questionType: "multiple_choice",
          imageUrl: null,
          selectedOptionId: "demo-en-option-3a",
          selectedOptionText: "$x^2 - 4$",
          textAnswer: null,
          correctOptionId: "demo-en-option-3a",
          correctOptionText: "$x^2 - 4$",
          isCorrect: true,
          pointsAwarded: 7,
          pointsPossible: 7,
          teacherComment: null,
        },
        {
          answerId: "demo-en-best-answer-4",
          questionId: "demo-en-question-4",
          questionText: "Factor: $x^2 + 5x + 6$",
          questionType: "short_answer",
          imageUrl: null,
          selectedOptionId: null,
          selectedOptionText: null,
          textAnswer: "(x+2)(x+3)",
          correctOptionId: null,
          correctOptionText: null,
          isCorrect: true,
          pointsAwarded: 3,
          pointsPossible: 3,
          teacherComment: "Nice fix - exactly what I was looking for!",
        },
      ],
    },
    answers: [
      {
        answerId: "demo-en-answer-1",
        questionId: "demo-en-question-1",
        questionText: "What is the expansion of $(x+3)^2$?",
        questionType: "multiple_choice",
        imageUrl: null,
        selectedOptionId: "demo-en-option-1b",
        selectedOptionText: "$x^2 + 6x + 9$",
        textAnswer: null,
        correctOptionId: "demo-en-option-1b",
        correctOptionText: "$x^2 + 6x + 9$",
        isCorrect: true,
        pointsAwarded: 5,
        pointsPossible: 5,
        teacherComment: null,
      },
      {
        answerId: "demo-en-answer-2",
        questionId: "demo-en-question-2",
        questionText: "Factor: $x^2 - 9$",
        questionType: "short_answer",
        imageUrl: null,
        selectedOptionId: null,
        selectedOptionText: null,
        textAnswer: "(x-3)(x+3)",
        correctOptionId: null,
        correctOptionText: null,
        isCorrect: true,
        pointsAwarded: 5,
        pointsPossible: 5,
        teacherComment: "Nice work! Correct use of the difference of squares.",
      },
      {
        answerId: "demo-en-answer-3",
        questionId: "demo-en-question-3",
        questionText: "What is the expansion of $(x-2)(x+2)$?",
        questionType: "multiple_choice",
        imageUrl: null,
        selectedOptionId: "demo-en-option-3a",
        selectedOptionText: "$x^2 - 4$",
        textAnswer: null,
        correctOptionId: "demo-en-option-3a",
        correctOptionText: "$x^2 - 4$",
        isCorrect: true,
        pointsAwarded: 7,
        pointsPossible: 7,
        teacherComment: null,
      },
      {
        answerId: "demo-en-answer-4",
        questionId: "demo-en-question-4",
        questionText: "Factor: $x^2 + 5x + 6$",
        questionType: "short_answer",
        imageUrl: null,
        selectedOptionId: null,
        selectedOptionText: null,
        textAnswer: "(x+2)(x+4)",
        correctOptionId: null,
        correctOptionText: null,
        isCorrect: false,
        pointsAwarded: 0,
        pointsPossible: 3,
        teacherComment:
          "Check your work: the numbers need to multiply to 6 and add to 5 - try the factors again.",
      },
    ],
  },
  // A retry that improves but doesn't fully fix everything - and is still
  // retriable, unlike demo-en-quiz-factoring above (attempts maxed out) -
  // two different points along the same feature, shown side by side.
  "demo-en-quiz-vectors": {
    attemptId: "demo-en-attempt-vectors",
    quizId: "demo-en-quiz-vectors",
    quizTitle: "Vectors",
    score: 10,
    maxScore: 20,
    submittedAt: isoDateTime(-20, 18, 5),
    attemptsUsed: 2,
    maxAttempts: null,
    canRetake: true,
    best: {
      score: 15,
      submittedAt: isoDateTime(-18, 18, 45),
      answers: [
        {
          answerId: "demo-en-vectors-best-answer-1",
          questionId: "demo-en-vectors-question-1",
          questionText: "If $\\vec{a} = (2, 3)$ and $\\vec{b} = (1, -1)$, find $\\vec{a} + \\vec{b}$.",
          questionType: "multiple_choice",
          imageUrl: null,
          selectedOptionId: "demo-en-vectors-option-1a",
          selectedOptionText: "(3, 2)",
          textAnswer: null,
          correctOptionId: "demo-en-vectors-option-1a",
          correctOptionText: "(3, 2)",
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: null,
        },
        {
          answerId: "demo-en-vectors-best-answer-2",
          questionId: "demo-en-vectors-question-2",
          questionText: "Compute the dot product $\\vec{a} \\cdot \\vec{b}$ for $\\vec{a} = (2, 3)$, $\\vec{b} = (1, -1)$.",
          questionType: "short_answer",
          imageUrl: null,
          selectedOptionId: null,
          selectedOptionText: null,
          textAnswer: "-1",
          correctOptionId: null,
          correctOptionText: null,
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: "Correct this time! You multiplied and added properly.",
        },
        {
          answerId: "demo-en-vectors-best-answer-3",
          questionId: "demo-en-vectors-question-3",
          questionText: "What is the magnitude of the vector $\\vec{a} = (3, 4)$?",
          questionType: "short_answer",
          imageUrl: null,
          selectedOptionId: null,
          selectedOptionText: null,
          textAnswer: "7",
          correctOptionId: null,
          correctOptionText: null,
          isCorrect: false,
          pointsAwarded: 0,
          pointsPossible: 5,
          teacherComment:
            "Still not quite - the magnitude is $\\sqrt{3^2+4^2}$, not the sum of the coordinates.",
        },
        {
          answerId: "demo-en-vectors-best-answer-4",
          questionId: "demo-en-vectors-question-4",
          questionText: "Are the vectors $(2, 4)$ and $(1, 2)$ parallel?",
          questionType: "true_false",
          imageUrl: null,
          selectedOptionId: "demo-en-vectors-option-4a",
          selectedOptionText: "Yes",
          textAnswer: null,
          correctOptionId: "demo-en-vectors-option-4a",
          correctOptionText: "Yes",
          isCorrect: true,
          pointsAwarded: 5,
          pointsPossible: 5,
          teacherComment: null,
        },
      ],
    },
    answers: [
      {
        answerId: "demo-en-vectors-answer-1",
        questionId: "demo-en-vectors-question-1",
        questionText: "If $\\vec{a} = (2, 3)$ and $\\vec{b} = (1, -1)$, find $\\vec{a} + \\vec{b}$.",
        questionType: "multiple_choice",
        imageUrl: null,
        selectedOptionId: "demo-en-vectors-option-1a",
        selectedOptionText: "(3, 2)",
        textAnswer: null,
        correctOptionId: "demo-en-vectors-option-1a",
        correctOptionText: "(3, 2)",
        isCorrect: true,
        pointsAwarded: 5,
        pointsPossible: 5,
        teacherComment: null,
      },
      {
        answerId: "demo-en-vectors-answer-2",
        questionId: "demo-en-vectors-question-2",
        questionText: "Compute the dot product $\\vec{a} \\cdot \\vec{b}$ for $\\vec{a} = (2, 3)$, $\\vec{b} = (1, -1)$.",
        questionType: "short_answer",
        imageUrl: null,
        selectedOptionId: null,
        selectedOptionText: null,
        textAnswer: "5",
        correctOptionId: null,
        correctOptionText: null,
        isCorrect: false,
        pointsAwarded: 0,
        pointsPossible: 5,
        teacherComment:
          "Check the formula: $\\vec{a} \\cdot \\vec{b} = a_1 b_1 + a_2 b_2$, not simple addition.",
      },
      {
        answerId: "demo-en-vectors-answer-3",
        questionId: "demo-en-vectors-question-3",
        questionText: "What is the magnitude of the vector $\\vec{a} = (3, 4)$?",
        questionType: "short_answer",
        imageUrl: null,
        selectedOptionId: null,
        selectedOptionText: null,
        textAnswer: "7",
        correctOptionId: null,
        correctOptionText: null,
        isCorrect: false,
        pointsAwarded: 0,
        pointsPossible: 5,
        teacherComment: null,
      },
      {
        answerId: "demo-en-vectors-answer-4",
        questionId: "demo-en-vectors-question-4",
        questionText: "Are the vectors $(2, 4)$ and $(1, 2)$ parallel?",
        questionType: "true_false",
        imageUrl: null,
        selectedOptionId: "demo-en-vectors-option-4a",
        selectedOptionText: "Yes",
        textAnswer: null,
        correctOptionId: "demo-en-vectors-option-4a",
        correctOptionText: "Yes",
        isCorrect: true,
        pointsAwarded: 5,
        pointsPossible: 5,
        teacherComment: null,
      },
    ],
  },
};

const SOPHIE: ParentDashboardData["kids"][number] = {
  student: {
    id: "demo-en-student-sophie",
    firstName: "Sophie",
    lastName: "Johnson",
    gradeLevel: "6th Grade",
    email: null,
    tuitionAmount: 70,
    withdrawnAt: null,
  },
  classes: [
    { id: "demo-en-class-grade6-math", name: "6th Grade Math", hoursPerWeek: 2, archivedAt: null },
  ],
  schedules: [
    { class_id: "demo-en-class-grade6-math", day: "Tue", time: "16:00" },
    { class_id: "demo-en-class-grade6-math", day: "Thu", time: "16:00" },
  ],
  attendance: [
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-3), status: "present" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-5), status: "present" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-10), status: "present" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-12), status: "late" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-17), status: "present" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-19), status: "present" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-24), status: "absent" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-31), status: "present" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-38), status: "present" },
    { class_id: "demo-en-class-grade6-math", class_name: "6th Grade Math", attendance_date: isoDate(-45), status: "late" },
  ],
  quizzes: [
    {
      id: "demo-en-quiz-fractions",
      title: "Working with Fractions",
      className: "6th Grade Math",
      completed: true,
      score: 19,
      maxScore: 20,
      submittedAt: isoDateTime(-9, 17, 20),
      quizDeleted: false,
      bestScore: 19,
      attemptsUsed: 1,
      maxAttempts: null,
      canRetake: false,
    },
    {
      id: "demo-en-quiz-sophie-decimals",
      title: "Decimal Numbers",
      className: "6th Grade Math",
      completed: true,
      score: 16,
      maxScore: 20,
      submittedAt: isoDateTime(-23, 16, 45),
      quizDeleted: false,
      // Retried once and improved - attempts used up.
      bestScore: 19,
      attemptsUsed: 2,
      maxAttempts: 2,
      canRetake: false,
    },
    {
      id: "demo-en-quiz-sophie-geometry",
      title: "Geometric Shapes",
      className: "6th Grade Math",
      completed: true,
      score: 20,
      maxScore: 20,
      submittedAt: isoDateTime(-37, 16, 15),
      quizDeleted: false,
      bestScore: 20,
      attemptsUsed: 1,
      maxAttempts: null,
      canRetake: false,
    },
    {
      id: "demo-en-quiz-sophie-equations",
      title: "Simple Equations",
      className: "6th Grade Math",
      completed: true,
      score: 17,
      maxScore: 20,
      submittedAt: isoDateTime(-44, 16, 30),
      quizDeleted: false,
      // Hasn't retried yet, but still can.
      bestScore: 17,
      attemptsUsed: 1,
      maxAttempts: 2,
      canRetake: true,
    },
    {
      id: "demo-en-quiz-sophie-ratios",
      title: "Ratios & Proportions",
      className: "6th Grade Math",
      completed: false,
      score: null,
      maxScore: 20,
      submittedAt: null,
      quizDeleted: false,
      bestScore: null,
      attemptsUsed: 0,
      maxAttempts: null,
      canRetake: false,
    },
  ],
  calendarEvents: [
    {
      id: "demo-en-event-sophie-extra",
      event_type: "extra_session",
      event_date: isoDate(3),
      start_time: "16:00",
      end_time: "17:00",
      class_id: "demo-en-class-grade6-math",
      class_name: "6th Grade Math",
      notes: "Getting ready for the test",
    },
  ],
};

const ALEX_AS_CHILD: ParentDashboardData["kids"][number] = {
  student: { ...ALEX.student, withdrawnAt: null },
  classes: ALEX.classes,
  schedules: ALEX.schedules,
  attendance: ALEX.attendance,
  quizzes: ALEX.quizzes,
  calendarEvents: ALEX.calendarEvents,
};

export const DEMO_EN_STUDENT_DASHBOARD: StudentDashboardData = ALEX;

export const DEMO_EN_PARENT_DASHBOARD: ParentDashboardData = {
  parent: {
    id: "demo-en-parent-lisa",
    name: "Lisa Johnson",
    email: "lisa.johnson@example.com",
    phone: "555-123-4567",
    isPrimary: true,
  },
  allParents: [
    {
      name: "Lisa Johnson",
      email: "lisa.johnson@example.com",
      phone: "555-123-4567",
      is_primary: true,
    },
    {
      name: "Mark Johnson",
      email: "mark.johnson@example.com",
      phone: "555-987-6543",
      is_primary: false,
    },
  ],
  kids: [ALEX_AS_CHILD, SOPHIE],
  balance: {
    amount: 25,
    monthlyAmount: 140,
    recentTransactions: [
      {
        id: "demo-en-txn-charge",
        type: "monthly_charge",
        amount: 140,
        description: `${monthName(-5)} tuition`,
        createdAt: isoDateTime(-5, 8, 0),
        receiptId: null,
      },
      {
        id: "demo-en-txn-payment",
        type: "payment",
        amount: -115,
        description: "Cash payment",
        createdAt: isoDateTime(-3, 10, 15),
        receiptId: "demo-en-receipt-recent",
      },
      {
        id: "demo-en-txn-charge-2",
        type: "monthly_charge",
        amount: 140,
        description: `${monthName(-35)} tuition`,
        createdAt: isoDateTime(-35, 8, 0),
        receiptId: null,
      },
      {
        id: "demo-en-txn-payment-2",
        type: "payment",
        amount: -140,
        description: "Card payment",
        createdAt: isoDateTime(-33, 11, 0),
        receiptId: "demo-en-receipt-month2",
      },
    ],
  },
  // The receipt itself stays in Greek - it's the real legal tax document
  // format the business issues to every client regardless of the client's
  // own language (see the file-level comment on ReceiptDocument), so this
  // mirrors lib/demo-data.ts's receipts almost verbatim, just addressed to
  // this demo's own family.
  receipts: [
    {
      id: "demo-en-receipt-recent",
      series: "Α",
      receipt_number: 47,
      issue_date: isoDate(-3),
      recipient_name: "Lisa Johnson",
      recipient_afm: null,
      recipient_address: null,
      family_id: "demo-en-family-johnson",
      total_amount: 115,
      vat_category: "exempt_article_27",
      payment_method: 3,
      notes: null,
      mydata_status: "submitted",
      mydata_mark: "400012399901234",
      mydata_uid: "demo-en-uid-47",
      mydata_error: null,
      mydata_submitted_at: isoDateTime(-3, 10, 20),
      mydata_environment: "production",
      mydata_last_verified_at: isoDateTime(-3, 10, 25),
      mydata_last_verified_ok: true,
      emailed_at: null,
      created_at: isoDateTime(-3, 10, 15),
      counts_toward_balance: true,
      lineItems: [
        {
          id: "demo-en-li-recent-1",
          student_id: "demo-en-student-alex",
          description: `Δίδακτρα ${greekMonthName(-3)} - Alex`,
          amount: 115,
          order_index: 0,
        },
      ],
    },
    {
      id: "demo-en-receipt-month2",
      series: "Α",
      receipt_number: 46,
      issue_date: isoDate(-33),
      recipient_name: "Lisa Johnson",
      recipient_afm: null,
      recipient_address: null,
      family_id: "demo-en-family-johnson",
      total_amount: 140,
      vat_category: "exempt_article_27",
      payment_method: 7,
      notes: null,
      mydata_status: "submitted",
      mydata_mark: "400012399900888",
      mydata_uid: "demo-en-uid-46",
      mydata_error: null,
      mydata_submitted_at: isoDateTime(-33, 11, 5),
      mydata_environment: "production",
      mydata_last_verified_at: isoDateTime(-33, 11, 10),
      mydata_last_verified_ok: true,
      emailed_at: null,
      created_at: isoDateTime(-33, 11, 0),
      counts_toward_balance: true,
      lineItems: [
        {
          id: "demo-en-li-month2-1",
          student_id: "demo-en-student-alex",
          description: `Δίδακτρα ${greekMonthName(-33)} - Alex`,
          amount: 90,
          order_index: 0,
        },
        {
          id: "demo-en-li-month2-2",
          student_id: "demo-en-student-sophie",
          description: `Δίδακτρα ${greekMonthName(-33)} - Sophie`,
          amount: 50,
          order_index: 1,
        },
      ],
    },
  ] satisfies Receipt[],
  business: {
    id: 1,
    business_name: "Modus — Φροντιστήριο Μαθηματικών",
    afm: "123456789",
    doy: "Καρδίτσας",
    activity_code: "85592000",
    address: "Καρδίτσα",
    city: "Καρδίτσα",
    postal_code: "43100",
    phone: "6971234567",
    updated_at: isoDateTime(-90, 9, 0),
  } satisfies BusinessProfile,
};
